version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - JWT_SECRET=secret1234
    volumes:
      - ./backend:/app
      # - /app/node_modules   

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

    volumes:
      - ./frontend:/app
      # - /app/node_modules  

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: net_project
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
